"""Three-layer initiative event system for Yunxi.

Events are prompt material only. They describe something Yunxi may want to
talk about, but the final proactive message must still be generated by an LLM.
"""

from __future__ import annotations

import json
import random
import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Iterable, Optional


DEFAULT_EVENT_LIBRARY_PATH = Path("data/initiative/life_events.json")
DEFAULT_ACTIVE_EVENT_LIMIT = 8


class InitiativeEventError(RuntimeError):
    """Raised when initiative event data is missing or malformed."""


class InitiativeEventLayer(Enum):
    """The three initiative event layers."""

    INNER_LIFE = "inner_life"
    SHARED_INTEREST = "shared_interest"
    MIXED = "mixed"


@dataclass(frozen=True)
class EventAffectDelta:
    """Event-driven affect delta."""

    valence: float = 0.0
    arousal: float = 0.0

    @classmethod
    def from_mapping(cls, data: object) -> "EventAffectDelta":
        """Build affect delta from JSON-compatible data."""
        if not isinstance(data, dict):
            return cls()
        return cls(
            valence=float(data.get("valence", 0.0)),
            arousal=float(data.get("arousal", 0.0)),
        )

    def to_dict(self) -> dict[str, float]:
        """Serialize affect delta."""
        return {"valence": self.valence, "arousal": self.arousal}


@dataclass(frozen=True)
class InitiativeTimeRules:
    """Time rules controlling when an event can be selected."""

    hours: tuple[int, int] | None = None
    weekday: bool | None = None
    weekend: bool | None = None

    @classmethod
    def from_mapping(cls, data: object) -> "InitiativeTimeRules":
        """Build time rules from JSON-compatible data."""
        if not isinstance(data, dict):
            return cls()
        hours_value = data.get("hours")
        hours: tuple[int, int] | None = None
        if isinstance(hours_value, list) and len(hours_value) == 2:
            hours = (int(hours_value[0]), int(hours_value[1]))
        return cls(
            hours=hours,
            weekday=_optional_bool(data.get("weekday")),
            weekend=_optional_bool(data.get("weekend")),
        )

    def matches(self, moment: datetime) -> bool:
        """Return whether these rules allow the given moment."""
        if self.weekday is True and moment.weekday() >= 5:
            return False
        if self.weekend is True and moment.weekday() < 5:
            return False
        if self.hours is None:
            return True
        start, end = self.hours
        hour = moment.hour
        if start <= end:
            return start <= hour <= end
        return hour >= start or hour <= end

    def to_dict(self) -> dict[str, object]:
        """Serialize time rules."""
        data: dict[str, object] = {}
        if self.hours is not None:
            data["hours"] = [self.hours[0], self.hours[1]]
        if self.weekday is not None:
            data["weekday"] = self.weekday
        if self.weekend is not None:
            data["weekend"] = self.weekend
        return data


@dataclass(frozen=True)
class InitiativeEvent:
    """A life event candidate that can feed proactive prompt generation."""

    event_id: str
    layer: InitiativeEventLayer
    category: str
    seed: str
    affect_delta: EventAffectDelta = field(default_factory=EventAffectDelta)
    time_rules: InitiativeTimeRules = field(default_factory=InitiativeTimeRules)
    tags: tuple[str, ...] = field(default_factory=tuple)
    cooldown_seconds: float = 21600.0
    source: str = ""

    @classmethod
    def from_mapping(cls, data: dict[str, object]) -> "InitiativeEvent":
        """Build and validate an event from JSON data.

        Raises:
            InitiativeEventError: If required event fields are missing.
        """
        event_id = _required_text(data, "id")
        layer = InitiativeEventLayer(_required_text(data, "layer"))
        category = _required_text(data, "category")
        seed = _required_text(data, "seed")
        return cls(
            event_id=event_id,
            layer=layer,
            category=category,
            seed=seed,
            affect_delta=EventAffectDelta.from_mapping(data.get("affect_delta", {})),
            time_rules=InitiativeTimeRules.from_mapping(data.get("time_rules", {})),
            tags=_string_tuple(data.get("tags", []), "tags"),
            cooldown_seconds=float(data.get("cooldown_seconds", 21600.0)),
            source=str(data.get("source", "")),
        )

    def to_prompt_context(self) -> str:
        """Render this event as LLM prompt material."""
        tags = ", ".join(self.tags) if self.tags else "none"
        return (
            "initiative_event:\n"
            f"- layer: {self.layer.value}\n"
            f"- category: {self.category}\n"
            f"- seed: {self.seed}\n"
            f"- tags: {tags}\n"
            f"- affect_delta: valence={self.affect_delta.valence:.1f}, "
            f"arousal={self.affect_delta.arousal:.1f}\n"
            "Use this only as context. Do not copy it verbatim; speak naturally as Yunxi."
        )


@dataclass
class InitiativeEventState:
    """Runtime state for selected initiative events."""

    last_selected_at: dict[str, float] = field(default_factory=dict)
    active_event_ids: list[str] = field(default_factory=list)
    selected_count: int = 0

    def to_dict(self) -> dict[str, object]:
        """Serialize runtime event state."""
        return {
            "last_selected_at": self.last_selected_at,
            "active_event_ids": self.active_event_ids,
            "selected_count": self.selected_count,
        }

    @classmethod
    def from_mapping(cls, data: object) -> "InitiativeEventState":
        """Deserialize runtime event state."""
        if not isinstance(data, dict):
            return cls()
        raw_last = data.get("last_selected_at", {})
        last_selected = {
            str(key): float(value)
            for key, value in raw_last.items()
        } if isinstance(raw_last, dict) else {}
        raw_active = data.get("active_event_ids", [])
        active = [str(item) for item in raw_active] if isinstance(raw_active, list) else []
        return cls(
            last_selected_at=last_selected,
            active_event_ids=active,
            selected_count=int(data.get("selected_count", 0)),
        )


class ThreeLayerInitiativeEventSystem:
    """Select initiative events from inner-life, shared-interest, and mixed layers."""

    def __init__(
        self,
        library_path: Path | str = DEFAULT_EVENT_LIBRARY_PATH,
        state_path: Path | str | None = None,
        rng: Optional[random.Random] = None,
    ):
        self.library_path = Path(library_path)
        self.state_path = Path(state_path) if state_path is not None else None
        self.rng = rng or random.Random()
        self.events = load_initiative_events(self.library_path)
        self.state = self._load_state()

    def select_event(
        self,
        *,
        moment: Optional[datetime] = None,
        preferred_layers: Optional[Iterable[InitiativeEventLayer]] = None,
        required_tags: Optional[Iterable[str]] = None,
    ) -> Optional[InitiativeEvent]:
        """Select an available event and record its cooldown state."""
        now = moment or datetime.now()
        timestamp = now.timestamp()
        candidates = self._available_events(
            moment=now,
            timestamp=timestamp,
            preferred_layers=preferred_layers,
            required_tags=required_tags,
        )
        if not candidates:
            return None
        selected = self.rng.choice(candidates)
        self.record_selected(selected, timestamp=timestamp)
        return selected

    def record_selected(self, event: InitiativeEvent, timestamp: Optional[float] = None) -> None:
        """Record that an event was selected."""
        selected_at = timestamp if timestamp is not None else time.time()
        self.state.last_selected_at[event.event_id] = selected_at
        if event.event_id in self.state.active_event_ids:
            self.state.active_event_ids.remove(event.event_id)
        self.state.active_event_ids.append(event.event_id)
        self.state.active_event_ids = self.state.active_event_ids[-DEFAULT_ACTIVE_EVENT_LIMIT:]
        self.state.selected_count += 1
        self.save_state()

    def build_prompt_context(self, event: Optional[InitiativeEvent]) -> str:
        """Render selected event context for proactive prompts."""
        if event is None:
            return ""
        return event.to_prompt_context()

    def save_state(self) -> None:
        """Persist runtime state if a state path is configured."""
        if self.state_path is None:
            return
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        self.state_path.write_text(
            json.dumps(self.state.to_dict(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    def _available_events(
        self,
        *,
        moment: datetime,
        timestamp: float,
        preferred_layers: Optional[Iterable[InitiativeEventLayer]],
        required_tags: Optional[Iterable[str]],
    ) -> list[InitiativeEvent]:
        preferred = set(preferred_layers or [])
        required = {tag for tag in (required_tags or []) if tag}
        candidates: list[InitiativeEvent] = []
        for event in self.events:
            if preferred and event.layer not in preferred:
                continue
            if required and not required.intersection(event.tags):
                continue
            if not event.time_rules.matches(moment):
                continue
            last_selected = self.state.last_selected_at.get(event.event_id)
            if last_selected is not None and timestamp - last_selected < event.cooldown_seconds:
                continue
            candidates.append(event)
        return candidates

    def _load_state(self) -> InitiativeEventState:
        if self.state_path is None or not self.state_path.exists():
            return InitiativeEventState()
        try:
            data = json.loads(self.state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise InitiativeEventError(f"Cannot load initiative event state: {self.state_path}") from exc
        return InitiativeEventState.from_mapping(data)


def load_initiative_events(path: Path | str = DEFAULT_EVENT_LIBRARY_PATH) -> list[InitiativeEvent]:
    """Load and validate initiative events from JSON."""
    event_path = Path(path)
    try:
        data = json.loads(event_path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise InitiativeEventError(f"Cannot read initiative event library: {event_path}") from exc
    except json.JSONDecodeError as exc:
        raise InitiativeEventError(f"Invalid initiative event JSON: {event_path}") from exc

    if not isinstance(data, list):
        raise InitiativeEventError(f"Initiative event library root must be a list: {event_path}")
    events = [
        InitiativeEvent.from_mapping(item)
        for item in data
        if isinstance(item, dict)
    ]
    if not events:
        raise InitiativeEventError(f"Initiative event library is empty: {event_path}")
    return events


def _required_text(data: dict[str, object], key: str) -> str:
    value = data.get(key)
    if not isinstance(value, str) or not value.strip():
        raise InitiativeEventError(f"Initiative event is missing required field: {key}")
    return value.strip()


def _string_tuple(value: object, field_name: str) -> tuple[str, ...]:
    if not isinstance(value, list):
        raise InitiativeEventError(f"Initiative event field must be a list: {field_name}")
    return tuple(str(item).strip() for item in value if str(item).strip())


def _optional_bool(value: object) -> bool | None:
    if value is None:
        return None
    return bool(value)
